name: my_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.3.0
  im_stepper: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "Addition"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/play.png"
  adaptive_icon_background: "#ffffff" # Optional for adaptive Android icons
  adaptive_icon_foreground: "assets/icon/play.png" # Optional for adaptive Android icons
  min_sdk_android: 21

flutter:
  uses-material-design: true
